### ISSUE TITLE
Question: Sample .secrets.* file

### ISSUE THREAD

**Issue by avra911** [andrewhowdencom/m2onk8s#26]
Hello,

Do you have a sample of what the file `.secrets.tar.gz.enc` should original contain, before being encrypted? Add it to the readme maybe?

Looking forward to test it!

Thanks!

**Comment by andrewhowdencom** [comment]
Hi @avra911; 

Managing expectations, this project is largely abandoned. (: The .secrets.tar.gz file containers some authentication stuff for managing CI -- Things such as a Google Cloud service account.

I've since switched a few things: 

1. I use helm to manage all Kubernetes projects. It's an amazing project, and I encourage you to check it out (: 
2. I now use git-crypt to manage secrets
3. I think I would opt for shifting most of this into two separate repositories: 
  a. A helm repository with the Magento 2 configuration (probably just drop in files over https://github.com/littlemanco/docker-apache-php)
  b. A build repository, which included the minimum required to compile a Magento 2 version plus the docker container. 

I previously raised this in the helm repository, and there was some interest in drawing up a chart for it. I'd be happy to collaborate there? Ref: https://github.com/kubernetes/charts/issues/205

**Comment by avra911** [comment]
Hi, @andrewhowdencom 

Thank you for your feedback! I am also using helm with custom images and gcloud sql as external service.

I wanted to give a drive test to this repository and I was missing the file format of secret variables.

I guess all it needs is a *.sample with variable names and empty quotes, for example:
```
MAGE_REPO_KEY=""
MAGE_REPO_SECRET=""
GCLOUD_USER=""
GCLOUD_SECRET=""
```

because encoded secret not only hides sensitive data, it is also loosing what stuff we need to create and secure ourselves.

Thanks,
R

**Comment by andrewhowdencom** [comment]
Hi @avra911, 

I'll find out. (: have modified the build to list the dir before and after the secrets file is unpacked, so we'll soon see. 

I can't unpack it locally, as I've since lost those env vars. Oops. 

https://travis-ci.org/andrewhowdencom/m2onk8s/builds/207378803

There might be a bit of futzing while I fix whatever's broken with the build

**Comment by andrewhowdencom** [comment]
Looking further, it appears that I'm already printing the contents of that tarball during the build. It's 
```
$ unpack-secrets.sh
application/auth.json # Probably for composer
.gcloud.json # Probably a robot account
.privkey # Probably an RSA Private key for pushing objects back to the git repo
```

It's extremely likely none of these credentials are valid any longer, but that gives you an idea what's in them.

**Comment by avra911** [comment]
alright, that give me an idea about it, thank a lot for the feedback!

Best regards!
